### ISSUE TITLE
missing exceptions manager

### ISSUE THREAD

**Issue by stethewwolf** [stethewwolf/Sapy#13]
Do you have any advice on this? or ideas ?

**Comment by RAJKUMAR18** [comment]
For a human factor it is necessary to add some exception handlers.
1-DataMgr(To check whether the entry exists before performing operation on them)

**Comment by RAJKUMAR18** [comment]
Are you on gitter.im we can converse over there

**Comment by RAJKUMAR18** [comment]
Sorry couldnt contribute  I was learning some python and database hadnling
