### ISSUE TITLE
mom : missing compare function

### ISSUE THREAD

**Issue by stethewwolf** [stethewwolf/Sapy#7]

**Comment by RAJKUMAR18** [comment]
Hi there @stethewwolf I saw your issue and I would like to help

**Comment by stethewwolf** [comment]
sure i send an invite to you 
ok i think this function could return like [strcompare](https://www.techonthenet.com/c_language/standard_library_functions/string_h/strcmp.php), the comparison should consist on : 
a.Direction * a.price >= b.Direction * b.Price

**Comment by RAJKUMAR18** [comment]
@stethewwolf  I am understanding the code.Will give you an update in a week

**Comment by stethewwolf** [comment]
ok, remember : open any issue you want  : )

**Comment by RAJKUMAR18** [comment]
What is the objective that is to be accomplished by this program?

**Comment by stethewwolf** [comment]
it aims to semplify your plans in matter of money .... it wil be  a simple  manager
